name: Auto Builder

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v3

      - name: Mensaje automático
        run: echo "Tu app se está actualizando automáticamente"